### ISSUE TITLE
More Feedback for observers 

### ISSUE THREAD

**Issue by jrmartin** [openworm/org.geppetto.simulation#39]
Users observing a simulation don't have much of a feedback. If controlling user decides to load a big simulation file it's presented with loading model dialog, but observing user only sees black screen with disabled controls unaware when a simulation will be shown/start. 

Maybe observing users should get a message telling them controlling user is re-loading another model, this way they will know there's something coming up instead of waiting looking at a black screen.

**Comment by tarelli** [comment]
Obsolete
